import EStyleSheet from "react-native-extended-stylesheet";
import { Dimensions, StyleSheet } from "react-native";

const containerWidth = Dimensions.get("window").width / 2;

const BUTTON_HEIGHT = 56;
const BORDER_RADIUS = 28;

export default EStyleSheet.create({
  $buttonBackgroundColorBase: "#006C51", // M3 Green 800
  $buttonBackgroundColorModifier: 0.1,
  $cancelbuttonBackgroundColorBase: "#BA1A1A", // M3 Red 700
  $cancelbuttonBackgroundColorModifier: 0.2,

  container: {
    backgroundColor: "$buttonBackgroundColorBase",
    width: 280,
    height: BUTTON_HEIGHT,
    borderRadius: BORDER_RADIUS,
    alignItems: "center",
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  outlinedContainer: {
    backgroundColor: "transparent",
    width: 280,
    height: BUTTON_HEIGHT,
    borderRadius: BORDER_RADIUS,
    alignItems: "center",
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "$buttonBackgroundColorBase",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  textContainer: {
    backgroundColor: "transparent",
    width: 280,
    height: BUTTON_HEIGHT,
    borderRadius: BORDER_RADIUS,
    alignItems: "center",
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  CDcontainer: {
    backgroundColor: "$buttonBackgroundColorBase",
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    marginRight: 0,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  button: {
    height: BUTTON_HEIGHT,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: BORDER_RADIUS,
  },
  CountDownButton: {
    height: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: 24,
  },
  buttonText: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    color: "#FFFFFF",
    letterSpacing: 0.1,
  },
  outlinedButtonText: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    color: "$buttonBackgroundColorBase",
    letterSpacing: 0.1,
  },
  textButtonText: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    color: "$buttonBackgroundColorBase",
    letterSpacing: 0.1,
  },
  fabContainer: {
    backgroundColor: "$buttonBackgroundColorBase",
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 24,
    right: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  extendedFabContainer: {
    backgroundColor: "$buttonBackgroundColorBase",
    height: 48,
    minWidth: 96,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    position: "absolute",
    right: 24,
    bottom: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  RoundButtonContainer: {
    backgroundColor: "#6FF9D1",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  CancelRoundButtonContainer: {
    backgroundColor: "$cancelbuttonBackgroundColorBase",
    height: 48,
    width: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  RoundButton: {
    height: 48,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: 24,
    paddingHorizontal: 16,
  },
  RoundButtonText: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    color: "#00201A",
    letterSpacing: 0.1,
  },
  CancelRoundButtonText: {
    fontFamily: "Roboto",
    fontWeight: "500",
    fontSize: 16,
    color: "#FFFFFF",
    letterSpacing: 0.1,
  },
  RepSecButtonContainer: {
    backgroundColor: "#6FF9D1",
    height: 48,
    borderRadius: 24,
    marginLeft: 8,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  RepSecButton: {
    height: 48,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: 24,
    paddingHorizontal: 16,
  },
  HomeHeader: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    height: 56,
    width: 56,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  }
});
